package org.personaltrainer.persistence.bean;
// Generated 08-sep-2013 9:45:08 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Muscle generated by hbm2java
 */
@Entity
@Table(name="muscle"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class Muscle  implements java.io.Serializable {


    // Fields    

     private int idMuscle;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private int optimistLock;
     private String name;
     private Set exerciseMuscles = new HashSet(0);


    // Constructors

    /** default constructor */
    public Muscle() {
    }

	/** minimal constructor */
    public Muscle(int idMuscle, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String name) {
        this.idMuscle = idMuscle;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.name = name;
    }
    
    /** full constructor */
    public Muscle(int idMuscle, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String name, Set exerciseMuscles) {
        this.idMuscle = idMuscle;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.name = name;
        this.exerciseMuscles = exerciseMuscles;
    }
    

   
    // Property accessors
    @Id
    @Column(name="ID_MUSCLE", unique=true, nullable=false, insertable=true, updatable=true)

    public int getIdMuscle() {
        return this.idMuscle;
    }
    
    public void setIdMuscle(int idMuscle) {
        this.idMuscle = idMuscle;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=45)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true)

    public int getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(int optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="NAME", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="muscle")

    public Set getExerciseMuscles() {
        return this.exerciseMuscles;
    }
    
    public void setExerciseMuscles(Set exerciseMuscles) {
        this.exerciseMuscles = exerciseMuscles;
    }
   








}
