package org.accessControl.persistence.bean;
// Generated 15-ago-2013 12:06:29 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * AccessControlResource generated by hbm2java
 */
@Entity
@Table(name="access_control_resource"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class AccessControlResource  implements java.io.Serializable {


    // Fields    

     private String codResource;
     private AccessControlResourceType accessControlResourceType;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private String nameType;
     private String description;
     private short optimistLock;
     private Set accessControlRights = new HashSet(0);


    // Constructors

    /** default constructor */
    public AccessControlResource() {
    }

	/** minimal constructor */
    public AccessControlResource(String codResource, AccessControlResourceType accessControlResourceType, Date createDate, Date updateDate, String updateUser, String updateProgram, short optimistLock) {
        this.codResource = codResource;
        this.accessControlResourceType = accessControlResourceType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
    }
    
    /** full constructor */
    public AccessControlResource(String codResource, AccessControlResourceType accessControlResourceType, Date createDate, Date updateDate, String updateUser, String updateProgram, String nameType, String description, short optimistLock, Set accessControlRights) {
        this.codResource = codResource;
        this.accessControlResourceType = accessControlResourceType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.nameType = nameType;
        this.description = description;
        this.optimistLock = optimistLock;
        this.accessControlRights = accessControlRights;
    }
    

   
    // Property accessors
    @Id
    @Column(name="COD_RESOURCE", unique=true, nullable=false, insertable=true, updatable=true, length=10)

    public String getCodResource() {
        return this.codResource;
    }
    
    public void setCodResource(String codResource) {
        this.codResource = codResource;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_RESOURCE_TYPE", unique=false, nullable=false, insertable=true, updatable=true)

    public AccessControlResourceType getAccessControlResourceType() {
        return this.accessControlResourceType;
    }
    
    public void setAccessControlResourceType(AccessControlResourceType accessControlResourceType) {
        this.accessControlResourceType = accessControlResourceType;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="NAME_TYPE", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getNameType() {
        return this.nameType;
    }
    
    public void setNameType(String nameType) {
        this.nameType = nameType;
    }
    @Column(name="DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true, length=500)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true, precision=3, scale=0)

    public short getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(short optimistLock) {
        this.optimistLock = optimistLock;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="accessControlResource")

    public Set getAccessControlRights() {
        return this.accessControlRights;
    }
    
    public void setAccessControlRights(Set accessControlRights) {
        this.accessControlRights = accessControlRights;
    }
   








}
