package org.accessControl.persistence.bean;
// Generated 15-ago-2013 12:06:29 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * AccessControlTypeBehavior generated by hbm2java
 */
@Entity
@Table(name="access_control_type_behavior"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class AccessControlTypeBehavior  implements java.io.Serializable {


    // Fields    

     private int idTypeBehavior;
     private AccessControlResourceType accessControlResourceType;
     private AccessControlAction accessControlAction;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private short optimistLock;


    // Constructors

    /** default constructor */
    public AccessControlTypeBehavior() {
    }

    
    /** full constructor */
    public AccessControlTypeBehavior(int idTypeBehavior, AccessControlResourceType accessControlResourceType, AccessControlAction accessControlAction, Date createDate, Date updateDate, String updateUser, String updateProgram, short optimistLock) {
        this.idTypeBehavior = idTypeBehavior;
        this.accessControlResourceType = accessControlResourceType;
        this.accessControlAction = accessControlAction;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
    }
    

   
    // Property accessors
    @Id
    @Column(name="ID_TYPE_BEHAVIOR", unique=true, nullable=false, insertable=true, updatable=true)

    public int getIdTypeBehavior() {
        return this.idTypeBehavior;
    }
    
    public void setIdTypeBehavior(int idTypeBehavior) {
        this.idTypeBehavior = idTypeBehavior;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_RESOURCE_TYPE", unique=false, nullable=false, insertable=true, updatable=true)

    public AccessControlResourceType getAccessControlResourceType() {
        return this.accessControlResourceType;
    }
    
    public void setAccessControlResourceType(AccessControlResourceType accessControlResourceType) {
        this.accessControlResourceType = accessControlResourceType;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_ACTION", unique=false, nullable=false, insertable=true, updatable=true)

    public AccessControlAction getAccessControlAction() {
        return this.accessControlAction;
    }
    
    public void setAccessControlAction(AccessControlAction accessControlAction) {
        this.accessControlAction = accessControlAction;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true, precision=3, scale=0)

    public short getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(short optimistLock) {
        this.optimistLock = optimistLock;
    }
   








}
