package org.accessControl.persistence.bean;
// Generated 15-ago-2013 12:06:29 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * AccessControlResourceType generated by hbm2java
 */
@Entity
@Table(name="access_control_resource_type"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class AccessControlResourceType  implements java.io.Serializable {


    // Fields    

     private String codResourceType;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private short optimistLock;
     private String nameType;
     private String description;
     private Set accessControlResources = new HashSet(0);
     private Set accessControlTypeBehaviors = new HashSet(0);


    // Constructors

    /** default constructor */
    public AccessControlResourceType() {
    }

	/** minimal constructor */
    public AccessControlResourceType(String codResourceType, Date createDate, Date updateDate, String updateUser, String updateProgram, short optimistLock) {
        this.codResourceType = codResourceType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
    }
    
    /** full constructor */
    public AccessControlResourceType(String codResourceType, Date createDate, Date updateDate, String updateUser, String updateProgram, short optimistLock, String nameType, String description, Set accessControlResources, Set accessControlTypeBehaviors) {
        this.codResourceType = codResourceType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.nameType = nameType;
        this.description = description;
        this.accessControlResources = accessControlResources;
        this.accessControlTypeBehaviors = accessControlTypeBehaviors;
    }
    

   
    // Property accessors
    @Id
    @Column(name="COD_RESOURCE_TYPE", unique=true, nullable=false, insertable=true, updatable=true, length=10)

    public String getCodResourceType() {
        return this.codResourceType;
    }
    
    public void setCodResourceType(String codResourceType) {
        this.codResourceType = codResourceType;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true, precision=3, scale=0)

    public short getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(short optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="NAME_TYPE", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getNameType() {
        return this.nameType;
    }
    
    public void setNameType(String nameType) {
        this.nameType = nameType;
    }
    @Column(name="DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true, length=500)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="accessControlResourceType")

    public Set getAccessControlResources() {
        return this.accessControlResources;
    }
    
    public void setAccessControlResources(Set accessControlResources) {
        this.accessControlResources = accessControlResources;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="accessControlResourceType")

    public Set getAccessControlTypeBehaviors() {
        return this.accessControlTypeBehaviors;
    }
    
    public void setAccessControlTypeBehaviors(Set accessControlTypeBehaviors) {
        this.accessControlTypeBehaviors = accessControlTypeBehaviors;
    }
   








}
