package org.accessControl.persistence.bean;
// Generated 15-ago-2013 12:06:29 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * AccessControlProfile generated by hbm2java
 */
@Entity
@Table(name="access_control_profile"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class AccessControlProfile  implements java.io.Serializable {


    // Fields    

     private String codProfile;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private String profileName;
     private String description;
     private short optimistLock;
     private Set accessControlRights = new HashSet(0);


    // Constructors

    /** default constructor */
    public AccessControlProfile() {
    }

	/** minimal constructor */
    public AccessControlProfile(String codProfile, Date createDate, Date updateDate, String updateUser, String updateProgram, short optimistLock) {
        this.codProfile = codProfile;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
    }
    
    /** full constructor */
    public AccessControlProfile(String codProfile, Date createDate, Date updateDate, String updateUser, String updateProgram, String profileName, String description, short optimistLock, Set accessControlRights) {
        this.codProfile = codProfile;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.profileName = profileName;
        this.description = description;
        this.optimistLock = optimistLock;
        this.accessControlRights = accessControlRights;
    }
    

   
    // Property accessors
    @Id
    @Column(name="COD_PROFILE", unique=true, nullable=false, insertable=true, updatable=true, length=10)

    public String getCodProfile() {
        return this.codProfile;
    }
    
    public void setCodProfile(String codProfile) {
        this.codProfile = codProfile;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=25)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="PROFILE_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=25)

    public String getProfileName() {
        return this.profileName;
    }
    
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }
    @Column(name="DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true, precision=3, scale=0)

    public short getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(short optimistLock) {
        this.optimistLock = optimistLock;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="accessControlProfile")

    public Set getAccessControlRights() {
        return this.accessControlRights;
    }
    
    public void setAccessControlRights(Set accessControlRights) {
        this.accessControlRights = accessControlRights;
    }
   








}
