package org.accessControl.persistence.bean;
// Generated 15-ago-2013 12:06:29 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * AccessControlRight generated by hbm2java
 */
@Entity
@Table(name="access_control_right"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class AccessControlRight  implements java.io.Serializable {


    // Fields    

     private int idRight;
     private AccessControlProfile accessControlProfile;
     private AccessControlResource accessControlResource;
     private AccessControlAction accessControlAction;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;


    // Constructors

    /** default constructor */
    public AccessControlRight() {
    }

    
    /** full constructor */
    public AccessControlRight(int idRight, AccessControlProfile accessControlProfile, AccessControlResource accessControlResource, AccessControlAction accessControlAction, Date createDate, Date updateDate, String updateUser, String updateProgram) {
        this.idRight = idRight;
        this.accessControlProfile = accessControlProfile;
        this.accessControlResource = accessControlResource;
        this.accessControlAction = accessControlAction;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
    }
    

   
    // Property accessors
    @Id
    @Column(name="ID_RIGHT", unique=true, nullable=false, insertable=true, updatable=true)

    public int getIdRight() {
        return this.idRight;
    }
    
    public void setIdRight(int idRight) {
        this.idRight = idRight;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_PROFILE", unique=false, nullable=false, insertable=true, updatable=true)

    public AccessControlProfile getAccessControlProfile() {
        return this.accessControlProfile;
    }
    
    public void setAccessControlProfile(AccessControlProfile accessControlProfile) {
        this.accessControlProfile = accessControlProfile;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_RESOURCE", unique=false, nullable=false, insertable=true, updatable=true)

    public AccessControlResource getAccessControlResource() {
        return this.accessControlResource;
    }
    
    public void setAccessControlResource(AccessControlResource accessControlResource) {
        this.accessControlResource = accessControlResource;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_ACTION", unique=false, nullable=false, insertable=true, updatable=true)

    public AccessControlAction getAccessControlAction() {
        return this.accessControlAction;
    }
    
    public void setAccessControlAction(AccessControlAction accessControlAction) {
        this.accessControlAction = accessControlAction;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
   








}
